### ISSUE TITLE
Personal Touch

### ISSUE THREAD

**Issue by josephgupkim** [alphaseinor/colmar#1]
I love the personal touch you added to your capstone project!
The hover effects, shape of the buttons, and color scheme; they're all great!
Not sure if you left them intentionally but the icons used for the mobile view up in the nav bar during the desktop version looks neat as well!
The customizations you implemented in this project show how much you've learned, great job!

**Comment by alphaseinor** [comment]
The mobile buttons are at the top for a reason (I hate hieroglyphics without at least some reference), they disappear as needed on the mobile site. If you notice I also used the font-awesome versions of the icons where possible to get the hover effect I wanted. 

Thank you very much
