### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [alphaseinor/colmar#4]
Your project was written very well and the visual appeal of your project is evidence!

- Your code is structured and organized.
- Consistency with whitespace and indentations with comments made it legible and easy to navigate.
- Loved the customized themes of your project; colors, effects, etc.
- Please do give the "Thesis Exhibit" articles some more room! They look squished right now.
- Add a viewport meta tag to the head of your index.html file to make sure your media queries are being applied!

Overall great work on your project, keep it up!

Grade: Exceed expectation!

**Comment by alphaseinor** [comment]
Fixed the issue with thesis
I'll consider the viewport meta tag. 

Thank you very much!
